import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { ThemeProvider, ThemeWrapper } from "@/context/ThemeContext";
import { FontSizeProvider } from "@/context/FontSizeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ThemeWrapper>
            <FontSizeProvider>
              <Header />
              {children}
            </FontSizeProvider>
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
